version: '3.8'

services:
  oauth2-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/oauth2-server
      - RP_ID=${RP_ID:-localhost}
      - ORIGIN=${ORIGIN:-https://localhost}
      - SESSION_SECRET=${SESSION_SECRET:-supersecretkey}
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: